Evaluation_Workshop_Final_CDA_C#/Controllers/AnimalsController.cs
using Evaluation_Workshop_Final_CDA_C_.Data;
using Evaluation_Workshop_Final_CDA_C_.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evaluation_Workshop_Final_CDA_C_.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly Evaluation_Workshop_Final_CDA_C_Context _context;

        public AnimalsController(Evaluation_Workshop_Final_CDA_C_Context context)
        {
            _context = context;
        }

        // GET: Animals
        public async Task<IActionResult> Index(string searchString, int? raceId)
        {
            var animalsQuery = _context.Animal.Include(a => a.Race).AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                animalsQuery = animalsQuery.Where(a => a.AnimalName.Contains(searchString));
            }

            if (raceId.HasValue)
            {
                animalsQuery = animalsQuery.Where(a => a.RaceId == raceId);
            }

            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentRaceId"] = raceId;

            return View(await animalsQuery.ToListAsync());
        }


        // GET: Animals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();
            var animal = await _context.Animal.Include(a => a.Race).FirstOrDefaultAsync(m => m.AnimalId == id);
            if (animal == null) return NotFound();
            return View(animal);
        }

        // GET: Animals/Create
        public async Task<IActionResult> Create()
        {
            var viewModel = new CreateAnimalViewModel
            {
                AvailableRaces = new SelectList(await _context.Race.ToListAsync(), "RaceId", "RaceName")
            };
            return View(viewModel);
        }

        // POST: Animals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAnimalViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var animal = new Animal
                {
                    AnimalName = viewModel.AnimalName,
                    AnimalDescription = viewModel.AnimalDescription,
                    RaceId = viewModel.RaceId
                };
                _context.Add(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            viewModel.AvailableRaces = new SelectList(await _context.Race.ToListAsync(), "RaceId", "RaceName", viewModel.RaceId);
            return View(viewModel);
        }


        // GET: Animals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();
            var animal = await _context.Animal.FindAsync(id);
            if (animal == null) return NotFound();
            ViewData["RaceId"] = new SelectList(await _context.Race.ToListAsync(), "RaceId", "RaceName", animal.RaceId);
            return View(animal);
        }


        // POST: Animals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Animal animalFromForm)
        {
            if (id != animalFromForm.AnimalId) return NotFound();

            if (ModelState.IsValid)
            {
                var animalToUpdate = await _context.Animal.FindAsync(id);
                if (animalToUpdate == null) return NotFound();

                animalToUpdate.AnimalName = animalFromForm.AnimalName;
                animalToUpdate.AnimalDescription = animalFromForm.AnimalDescription;
                animalToUpdate.RaceId = animalFromForm.RaceId;
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalExists(animalFromForm.AnimalId)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["RaceId"] = new SelectList(await _context.Race.ToListAsync(), "RaceId", "RaceName", animalFromForm.RaceId);
            return View(animalFromForm);
        }

        // GET: Animals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            var animal = await _context.Animal.Include(a => a.Race).FirstOrDefaultAsync(m => m.AnimalId == id);
            if (animal == null) return NotFound();
            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var animal = await _context.Animal.FindAsync(id);
            if (animal != null) _context.Animal.Remove(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AnimalExists(int id)
        {
            return _context.Animal.Any(e => e.AnimalId == id);
        }
    }
}

Evaluation_Workshop_Final_CDA_C#/Controllers/HomeController.cs
using Evaluation_Workshop_Final_CDA_C_.Data;
using Evaluation_Workshop_Final_CDA_C_.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Evaluation_Workshop_Final_CDA_C_.Controllers
{
    public class HomeController : Controller
    {
        private readonly Evaluation_Workshop_Final_CDA_C_Context _context;

        public HomeController(Evaluation_Workshop_Final_CDA_C_Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["RacesList"] = new SelectList(await _context.Race.ToListAsync(), "RaceId", "RaceName");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Evaluation_Workshop_Final_CDA_C#/Controllers/RacesController.cs
using Evaluation_Workshop_Final_CDA_C_.Data;
using Evaluation_Workshop_Final_CDA_C_.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Evaluation_Workshop_Final_CDA_C_.Controllers
{
    public class RacesController : Controller
    {
        private readonly Evaluation_Workshop_Final_CDA_C_Context _context;

        public RacesController(Evaluation_Workshop_Final_CDA_C_Context context)
        {
            _context = context;
        }

        // GET: Races
        public async Task<IActionResult> Index()
        {
            return View(await _context.Race.ToListAsync());
        }

        // GET: Races/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Race
                .FirstOrDefaultAsync(m => m.RaceId == id);
            if (race == null)
            {
                return NotFound();
            }

            return View(race);
        }

        // GET: Races/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Races/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRaceViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var race = new Race
                {
                    RaceName = viewModel.RaceName,
                    RaceDescription = viewModel.RaceDescription
                };

                _context.Add(race);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        // GET: Races/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Race.FindAsync(id);
            if (race == null)
            {
                return NotFound();
            }

            return View(race);
        }

        // POST: Races/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RaceId,RaceName,RaceDescription")] Race raceFromForm)
        {
            if (id != raceFromForm.RaceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var raceToUpdate = await _context.Race.FindAsync(id);
                if (raceToUpdate == null)
                {
                    return NotFound("Impossible de trouver la race à mettre à jour.");
                }
                raceToUpdate.RaceName = raceFromForm.RaceName;
                raceToUpdate.RaceDescription = raceFromForm.RaceDescription;

                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaceExists(raceFromForm.RaceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(raceFromForm);
        }

        // GET: Races/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Race
                .FirstOrDefaultAsync(m => m.RaceId == id);
            if (race == null)
            {
                return NotFound();
            }

            return View(race);
        }

        // POST: Races/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var race = await _context.Race.FindAsync(id);
            if (race != null)
            {
                _context.Race.Remove(race);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RaceExists(int id)
        {
            return _context.Race.Any(e => e.RaceId == id);
        }
    }
}

Evaluation_Workshop_Final_CDA_C#/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center mb-4 bg-light rounded-3">
    <div class="container-fluid">
        <h1 class="fw-bold">Projet d'Évaluation</h1>
    </div>
</div>

@* Section avec la recherche par nom ou race *@
<div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">Trouver un Animal</h1>
    <p class="col-md-8 fs-4">
        Utilisez les filtres ci-dessous pour rechercher un animal spécifique par son nom ou sa race.
    </p>

    <hr class="my-4">
    <form asp-controller="Animals" asp-action="Index" method="get">
        <div class="row align-items-end g-3">
            <div class="col-md">
                <label for="searchString" class="form-label">Nom de l'animal</label>
                <input type="text" name="searchString" class="form-control" placeholder="Ex: Rex, Whiskers...">
            </div>
            <div class="col-md">
                <label for="raceId" class="form-label">Race</label>
                <select name="raceId" class="form-select" asp-items="@(ViewData["RacesList"] as SelectList)">
                    <option value="">Toutes les races</option>
                </select>
            </div>
            <div class="col-md-auto">
                <button type="submit" class="btn btn-primary btn-lg">
                    <i class="bi bi-search"></i> Rechercher
                </button>
            </div>
        </div>
    </form>

</div>

@* Section avec les cartes de navigation vers les CRUDs *@
<div class="row align-items-md-stretch">

    <div class="col-md-6 mb-4">
        <div class="card h-100 shadow-sm">
            <div class="card-body d-flex flex-column">
                <h4 class="card-title">Gestion des Animaux</h4>
                <p class="card-text flex-grow-1">
                    Accédez à la liste complète des animaux. Vous pouvez en créer de nouveaux,
                    modifier leurs informations ou les supprimer de la base de données.
                </p>
                <a class="btn btn-primary" asp-controller="Animals" asp-action="Index">
                    Gérer les Animaux <i class="bi bi-arrow-right-circle"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="col-md-6 mb-4">
        <div class="card h-100 shadow-sm">
            <div class="card-body d-flex flex-column">
                <h4 class="card-title">Gestion des Races</h4>
                <p class="card-text flex-grow-1">
                    Accédez à la liste des races. Vous pouvez ajouter de nouvelles races,
                    les éditer ou les supprimer.
                </p>
                <a class="btn btn-primary" asp-controller="Races" asp-action="Index">
                    Gérer les Races <i class="bi bi-arrow-right-circle"></i>
                </a>
            </div>
        </div>
    </div>

</div>